# Copyright 2023 William Perron. All rights reserved. MIT License.
dist:
  name: otelcol-dev
  description: Basic Otel Collector for development
  otelcol_version: 0.95.0
  version: 0.2.0-rc1
  output_path: ./bin/otelcol-dev

exporters:
  - gomod:
      # NOTE: Prior to v0.86.0 use the `loggingexporter` instead of `debugexporter`.
      go.opentelemetry.io/collector/exporter/debugexporter v0.95.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.95.0
  - gomod:
      go.wperron.io/sqliteexporter v0.2.0-rc1 # use the exporter from this repo

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.95.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.95.0
