receivers:
  otlp:
    protocols:
      grpc:
      http:

# processors:
#   batch:

exporters:
  debug:
  sqlite:
    path: something.db

service:
  pipelines:
    traces:
      receivers: [otlp]
      # processors: [batch]
      exporters: [debug, sqlite]
